### ISSUE TITLE
notes only minimal version?

### ISSUE THREAD

**Issue by atomGit** [sapristi/journal-startpage#9]
hi Mathias - i'm wondering if you might consider creating a minimalist version of the add-on which supports only notes (in markdown)?

**Comment by sapristi** [comment]
Hello,
what exactly would you expect from a "minimalist" version ? E.g. hiding the task (and maybe calendar) would already give a more minimal UI, without needing much refactoring.

**Comment by atomGit** [comment]
options to disable everything except the note area would be fine, though i suppose that could be done now with css? i didn't try it yet

**Comment by sapristi** [comment]
Well the top-panel holds the settings button, so hiding it could be troublesome.  Otherwise yes css may be a solution, panels do not have ids but that could be added.

**Comment by sapristi** [comment]
I've done something you can try at https://sapristi.github.io/journal-startpage/index.html (added `Hide tasks` and 
`Minimal top-panel` settings toggle)

**Comment by sapristi** [comment]
Available in latest version

**Comment by atomGit** [comment]
sorry for not getting back to you on this - real-life stuff - i'll be testing in the next day or so

**Comment by atomGit** [comment]
new version looks good - fantastic CSS there!

it's way more then i need, but it'll work - maybe if i get ambitious i'll attempt to hack it and trim it down to notes only capability

**Comment by sapristi** [comment]
> sorry for not getting back to you on this - real-life stuff - i'll be testing in the next day or so

No worries :)

I forgot to add  ids to the different zones, but I'll try to do that, it would make it much easier to further customize.

**Comment by sapristi** [comment]
Although it seems most css customization extensions don't support overriding css for the startpage (at least for firefox) - can you keep me updated if you manage to do that ?
Otherwise that would mean adding an input for custom css.
